# Site settings
title: Bryan T. Weinstein
email: btweinstein@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Bryan Weinstein's professional website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  btweinstein

# Build settings
markdown: kramdown
